language: csharp
solution: TravisTest.sln
before_install:
  # Get KSP DLL package from Google Drive
  - wget --no-check-certificate --quiet "https://drive.google.com/uc?export=download&id=${GDRIVE_DLL_PACKAGE_ID}" -O KSP_DLLs.zip
  # Unzip
  - unzip -P ${DLL_PACKAGE_ZIP_PASSPHRASE} KSP_DLLs.zip
  - mkdir -p TravisTest/bin/Release/
  - mv KSP_DLLs/* TravisTest/bin/Release/
after_success:
  - mkdir -p GameData/TravisTest/Plugins
  - echo "this is a readme" > GameData/TravisTest/readme.txt
  - cp TravisTest/bin/Release/TravisTest.dll GameData/TravisTest/Plugins
  - zip -r TravisTest.zip GameData
  - unzip -l TravisTest.zip
