language: csharp
solution: TravisTest.sln
before_install:
  # Create project name
  - export PROJECT_NAME="$(echo ${TRAVIS_REPO_SLUG} | sed 's/^[A\-z0\-9]*\///')"
  # Get KSP DLL package from Google Drive
  - wget --no-check-certificate --quiet "https://drive.google.com/uc?export=download&id=${GDRIVE_DLL_PACKAGE_ID}" -O KSP_DLLs.zip
  # Unzip
  - unzip -P ${DLL_PACKAGE_ZIP_PASSPHRASE} KSP_DLLs.zip
  - mkdir -p TravisTest/bin/Release/
  - mkdir -p TravisTestTests/bin/Release/
  - cp KSP_DLLs/${KSP_VERSION}/* TravisTest/bin/Release/
  - cp KSP_DLLs/${KSP_VERSION}/* TravisTestTests/bin/Release/
install:
  - nuget restore ${TRAVIS_SOLUTION}
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ${TRAVIS_SOLUTION}
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./TravisTestTests/bin/Release/TravisTestTests.dll
after_success:
  - mkdir release
  - mkdir zip_release
  - cp -R GameData release
  - echo "this is a readme" > release/GameData/${PROJECT_NAME}/readme.txt
  - mkdir -p release/GameData/${PROJECT_NAME}/Plugins
  - cp TravisTest/bin/Release/TravisTest.dll release/GameData/${PROJECT_NAME}/Plugins
  - (cd release && zip -r ../zip_release/${PROJECT_NAME}_dev_${TRAVIS_BUILD_NUMBER}.zip GameData)
  - ls zip_release
deploy:
  provider: bintray
  file: bintray_deploy.json
  user: blowfishpro
  key:
    secure: "j7uWv56T3XUgWd1BKASl/RHFhsWzTv0wxjIcX5e2vu2YsHmKSALAspK2umru92dpzDxa4mrw+uZEwU034FZEJZwd8evKq1zcKTzuveMM5SYbGmDQkqb2bmP0qd+Oc46+YqZKLaH8axfqYC4QnsfYJ/EErAA1zEkgQUM3V8rIBM4a3y8p1LXZBJ8z7qdvbNV0tPrXHO3kBFRc5fnetnnoMicUfuAR3BaIJDdOggPWe07IoLdChyFijc48enIN/cabptuiHXqcSvcS/2TKHwH7AadpIcGnq/CJjXaQLz6RnjHP493HT9qIpDIEp/TdPu9XKpc7fi82Pf+gNjbVZInilYZkg768ZDPJR6R3TStRoBmKsWphy8sbNb60efqhI3dpxAxj1m9Vijo7NA8naoglcnBL7rtjLQBYDewXd1HiJQ6g9F3KKVdWxyWl3MnMNAagQpd639HdjKr918On+uO9cpmAuCEZ3HLTAFliwmmStg0oaXMMpa7ObYU5LH3uDj1rihkbQGFMV9qV6JCT8UmKKSejc++8O9vta5vOlOOs7lTZVOTMHLPcKnhAFCYq81pYuxB4hRqjgZGzpCF0oxXkPwjiQNQVJUHwWuKOVCokkUbq3sUWEii3sTPpEhkQ7J7x45LVNhdQEjJdFOpTCOLU1yXv43ta2qlGizkiPO2FkAg="
